---
# tasks file for openvpn-openwrt

#- name: update opkg chache
#  raw: '[ "$(ls -A /var/opkg-lists/)" ] || opkg update'
#  changed_when: false
#TODO install openvpn-openssl

- name: Creazione del certificato con easy_rsa
  import_role:
    name: openwrt-uci

- name: Includo task per client
  include_tasks: client.yml
  when: openwrt_openvpn_client

- name: Includo task per server
  include_tasks: server.yml
  when: openwrt_openvpn_server



