---
# handlers file for openvpn-openwrt
- name: uci commit
  raw: uci commit 

- name: restart openvpn
  raw: /etc/init.d/openvpn restart

- name: reload network
  raw: /etc/init.d/network reload

- name: reload firewall
  raw: /etc/init.d/firewall reload
